apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-form-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: registration-form
  template:
    metadata:
      labels:
        app: registration-form
    spec:
      containers:
        - name: registration-form
          image: ramyareddy120/sample-2026:latest
          ports:
            - containerPort: 5000